export default function PrivacyPolicy() {
    return (
        <div className="flex justify-center">
            <div className="mt-32 mb-16 flex flex-col rounded-lg max-w-4xl bg-white shadow-[0px_0px_40px_0px_rgba(0,0,0,0.08)] dark:bg-dark-2 p-7">
                <p className="text-2xl font-bold mb-4">Terms of Service</p>
                <p className="text-xl font-bold mb-1">1. Introduction </p>
                <p className="mb-4">Welcome to Time for Music! By using our app, you agree to comply with and be bound by the following terms and conditions. Please review them carefully.</p>

                <p className="text-xl font-bold mb-1">2. Description of Service </p>
                <p className="mb-4">Time for Music is an app that generates physical QR cards based on your Spotify playlists. By using our service, you acknowledge and agree to the following terms.</p>

                <p className="text-xl font-bold mb-1">3. Return Policy </p>
                <p className="mb-4">
                    Due to the nature of our digital and / or tailor - made products, we do not accept returns and do not offer refunds for any versions of our QR music cards. Once a product has been delivered, it is considered final and non - refundable.
                    <br /> <br />
                    If you are not satisfied with your purchase of a playlist because of printing mistakes, we are able to send you a digital replacement.
                </p>

                <p className="text-xl font-bold mb-1">4. Digital Version Restrictions </p>
                <p className="mb-4">The digital PDF version of Time for Music cards is for personal use only. It is strictly prohibited to copy, sell, distribute or share the digital PDF version with others. Each digital version is tied to a single purchase and should only be used by the purchaser.</p>

                <p className="text-xl font-bold mb-1">5. Data Accuracy </p>
                <p className="mb-4">Time for Music imports data from external sources, such as Spotify. We do not take responsibility for the accuracy of the data on the cards generated. Users are responsible for verifying the correctness of the information.</p>

                <p className="text-xl font-bold mb-1">6. QR Link Functionality </p>
                <p className="mb-4">
                    While we strive to ensure that the QR links generated by Time for Music are functional, we cannot guarantee that these links will continue to work in the future. Changes in external services or other factors beyond our control may affect link functionality.
                </p>

                <p className="text-xl font-bold mb-1">7. User Responsibilities </p>
                <p className="mb-4">
                    Users must ensure they have the necessary rights to the playlists they use with Time for Music. By using our service, you confirm that you have the legal right to use and share the content in your playlists.
                </p>

                <p className="text-xl font-bold mb-1">8. Privacy Policy </p>
                <p className="mb-4">
                    Your privacy is important to us. Please refer to our Privacy Policy for information on how we collect, use, and protect your personal data.
                </p>

                <p className="text-xl font-bold mb-1">9. Intellectual Property </p>
                <p className="mb-4">
                    All content, trademarks, and data provided by Time for Music are the property of Time for Music or its licensors. Users retain ownership of their playlists and any content they provide.
                </p>

                <p className="text-xl font-bold mb-1">10. Limitation of Liability </p>
                <p className="mb-4">
                    Time for Music is not liable for any direct, indirect, incidental, or consequential damages arising from the use of our service. This includes, but is not limited to, any errors or omissions in the content, loss of data, or any other loss or damage incurred as a result of using our app.
                </p>

                <p className="text-xl font-bold mb-1">11. Changes to Terms </p>
                <p className="mb-4">
                    We reserve the right to modify these terms and conditions at any time. Users will be notified of any changes through our app or via email. Continued use of the app after changes have been made constitutes acceptance of the new terms.
                </p>

                <p className="text-xl font-bold mb-1">12. Governing Law </p>
                <p className="mb-4">
                    These terms and conditions are governed by and construed in accordance with the laws of The Netherlands. Any disputes arising from these terms will be subject to the exclusive jurisdiction of the courts of The Netherlands.
                </p>

                <p className="text-xl font-bold mb-1">13. Termination </p>
                <p className="mb-4">
                    We reserve the right to terminate or suspend access to Time for Music at our sole discretion, without prior notice or liability, for any reason, including if you breach the terms.
                </p>

                <p className="text-xl font-bold mb-1">14. Contact Information </p>
                <p className="mb-4">
                    If you have any questions about these terms and conditions, please contact us.
                </p>
            </div>
        </div>
    )
}

